version: 'latest'

# 1. Definir las redes personalizadas
networks:
  postgres-compose-network:
    driver: bridge

services:
# Definición del servicio postgres
  postgres:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: servicios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin    
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
     - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - postgres-compose-network